spring:
  profiles:
    active:
    - dev

---

spring:
  profiles:
  application:
    name: micro-service-config-dev

---

spring:
  profiles:
  application:
    name: micro-service-config-test

---

spring:
  profiles:
  application:
    name: micro-service-config-prod
