spring:
  profiles:
    active:
    - dev




---

spring:
   profiles: dev
   application:
    name: micro-servicecloud-dept-config-dev
   datasource:
       type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
       driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
       url: jdbc:mysql://192.168.1.197:3306/cloudDB01?useUnicode=true&characterEncoding=utf-8   # 数据库名称
       username: dev
       password: dev
       dbcp2:
         min-idle: 5                                           # 数据库连接池的最小维持连接数
         initial-size: 5                                       # 初始化连接数
         max-total: 5                                          # 最大连接数
         max-wait-millis: 200                                # 等待连接获取的最大超时时间
         validation-query: select 1
         validation-query-timeout: 5000
         test-while-idle: false
server:
  port: 8004

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.qs.game.entiy    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/
  instance:
    instance-id: dept-provider8004
    prefer-ip-address: true

---

spring:
   profiles: test
   application:
    name: micro-servicecloud-dept-config-test
   datasource:
       type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
       driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
       url: jdbc:mysql://192.168.1.197:3306/cloudDB02?useUnicode=true&characterEncoding=utf-8   # 数据库名称
       username: dev
       password: dev
       dbcp2:
         min-idle: 5                                           # 数据库连接池的最小维持连接数
         initial-size: 5                                       # 初始化连接数
         max-total: 5                                          # 最大连接数
         max-wait-millis: 200                                # 等待连接获取的最大超时时间
         validation-query: select 1
         validation-query-timeout: 5000
         test-while-idle: false
server:
  port: 8005

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.qs.game.entiy    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/
  instance:
    instance-id: dept-provider8005
    prefer-ip-address: true


---

spring:
   profiles: prod
   application:
    name: micro-servicecloud-dept-config-prod
   datasource:
       type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
       driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
       url: jdbc:mysql://192.168.1.197:3306/cloudDB03?useUnicode=true&characterEncoding=utf-8   # 数据库名称
       username: dev
       password: dev
       dbcp2:
         min-idle: 5                                           # 数据库连接池的最小维持连接数
         initial-size: 5                                       # 初始化连接数
         max-total: 5                                          # 最大连接数
         max-wait-millis: 200                                # 等待连接获取的最大超时时间
         validation-query: select 1
         validation-query-timeout: 5000
         test-while-idle: false
server:
  port: 8006

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.qs.game.entiy    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/
  instance:
    instance-id: dept-provider8006
    prefer-ip-address: true
