spring:
  profiles:
    active:
    - dev

---

spring:
  profiles: dev
  application:
    name: micro-service-config-dev

---

spring:
  profiles: test
  application:
    name: micro-service-config-test

---

spring:
  profiles: prod
  application:
    name: micro-service-config-prod
