server:
  port: 9527

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/
  instance:
      instance-id: zuul-server9527
      prefer-ip-address: true
spring:
  application:
    name: zuul-server

#zuul.routes.userservice.path=/user/**
#zuul.routes.userservice.strPrefix=true
#zuul.routes.userservice.url=http://localhost:9001/user
#zuul.routes.orgservice.path=/org/**
#zuul.routes.orgservice.strPrefix=true
#zuul.routes.orgservice.url=http://localhost:9002/org

zuul:
  routes:
    micro-servicecloud-dept-consumer:
      path: /consumer/**
      strPrefix: true
      url: http://127.0.0.1:80/consumer

info:
  app.name: zuul-server-9527
  company.name: qs.game
  build.artifactId: "@project.artifactId@"
  build.version: "@project.version@"
  spring-boot-version: "@project.parent.version@"
