server:
  port: 9527

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/
  instance:
      instance-id: zuul-server9527
      prefer-ip-address: true
spring:
  application:
    name: zuul-server

zuul:
  prefix: /qs
  ignored-services: "*"
  routes:
    mydept.serviceId: micro-servicecloud-dept
    mydept.path: /game/**


info:
  app.name: zuul-server-9527
  company.name: qs.game
  build.artifactId: "@project.artifactId@"
  build.version: "@project.version@"
  spring-boot-version: "@project.parent.version@"
