server:
  port: 3344

spring:
  application:
    name:  micro-servicecloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zunzhuowei/micro-service.git #GitHub上面的git仓库名字
          searchPaths: github-config-file  # 查找git仓库对应的目录
          default-label: master

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/
  instance:
      instance-id: micro-servicecloud-config-server3344
      prefer-ip-address: true
info:
  app.name: micro-servicecloud-config-server
  company.name: qs.game
  build.artifactId: "@project.artifactId@"
  build.version: "@project.version@"
  spring-boot-version: "@project.parent.version@"


# http://127.0.0.1:3344/application-test.yml