server:
  port: 80
spring:
  application:
    name: micro-servicecloud-dept-consumer
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
      instance-id: dept-consumer7001
      prefer-ip-address: true
info:
  app.name: micro-servicecloud-dept-consumer
  company.name: qs.game
  build.artifactId: $project.artifactId$
  build.version: $project.version$
